### ISSUE TITLE
Handle inline output

### ISSUE THREAD

**Issue by art049** [tmarktaylor/phmdoctest#1]
Hello, thanks for this project.

Would it possible to handle inline output ?
For example:
\```python
print("Hello world !")
#> Hello world !
\```
The expected output would be "Hello world !"

I saw that phm doesn't do Python console >>>, ...
Would you consider it anyway ?
BTW, I'd be happy to help

**Comment by tmarktaylor** [comment]
Hello,

Thanks for suggesting doing python console. An example would look like this in Markdown.
``````
```pycon
>>> print("Hello world !")
>>> Hello world !
```
``````
phmdoctest would generate a pytest test function for each pycon fenced code block. The test function will invoke Python standard library doctest. Each pycon block would be tested independently. Note there is no need for a blank line at the bottom of the pycon block. The blank line would be required by doctest.testfile('my-markdown-file.md') to indicate the end of the output.

I don't recognize the #> notation In the example at the top of the issue. It looks like a python comment that would have special meaning to phmdoctest.

**Comment by art049** [comment]
Wow thanks a lot for this ! #2
