### ISSUE TITLE
Consider using pytest dynamic test discovery

### ISSUE THREAD

**Issue by ssbarnea** [tmarktaylor/phmdoctest#14]
Pytest plugins can easily generate tests dynamically during test discovery. This means that it should be no need to compile markdown files into pytests. When the plugin is installed it should only discover tests inside markdown files and report them back to pytest.

I used a similar approach for exposing [molecule](https://github.com/ansible-community/pytest-molecule/blob/master/pytest_molecule/__init__.py#L126) tests as pytest tests and worked quite nice.

The reason I am proposing this is because I do not want to add extra compilation steps before running pytest, it does make the development experience harder and more prone to mistakes (like missing to recompile them).

**Comment by tmarktaylor** [comment]
Phmdoctest can be called from Python code. The function **simulator.run_and_pytest()** has an option to write the generated pytest file to a temporary directory and run pytest on it there. Please see [Call from Python](https://tmarktaylor.github.io/phmdoctest/#call-from-python). Try with the just released phmdoctest 1.2.1 which has bug fixes to this function.

**Comment by tmarktaylor** [comment]
Release 1.3.0 adds 2 pytest fixtures that work together to produce a pytest file from Markdown in memory and run it with pytest's pytester fixture.
