### ISSUE TITLE
directory usage

### ISSUE THREAD

**Issue by garfieldnate** [tmarktaylor/phmdoctest#21]
Hi, I like your project! My repository contains a docs/ directory with nested subdirectories of markdown files (documentation managed with Portray). It would be useful if there were a command to generate tests for an entire directory so that I don't have to  call `phmdoctest` for each one individually. The simplest thing would probably be to output to a directory which directly mirrors the structure of the input directory.

**Comment by tmarktaylor** [comment]
Hello,

Please have a look at the project pytest-phmdoctest https://github.com/tmarktaylor/pytest-phmdoctest which might satisfy your use case. It is a pytest plugin. It can process multiple Markdown files from different directories in a single pytest invocation.

Please be aware that breaking changes are planned for pytest-phmdoctest.  Please see its first issue.

To generate files and test them later try `pytest --phmdoctest --phmdoctest-save DIRECTORY`. That command will be revised in version 1.0.0.

**Comment by garfieldnate** [comment]
Works great, thanks for the tip!
