### ISSUE TITLE
how to add pytest markers

### ISSUE THREAD

**Issue by garfieldnate** [tmarktaylor/phmdoctest#23]
We mark our tests that use a network so that we can choose not to run them sometimes (because they are slow and require network connectivity). We use a custom [pytest attribute](https://docs.pytest.org/en/6.2.x/mark.html) `@pytest.mark.network`.

Many of the code blocks the documentation I'm writing also require a network connection to run, so I'd like to mark the output test methods with `@pytest.mark.network`. Is there a way to do this?

**Comment by tmarktaylor** [comment]
The first thing I am thinking of is adding a new **directive** called `<!--phmdoctest-mark.ATTRIBUTE-->` where ATTRIBUTE is replaced with a valid Python attribute identifier. The latest version **directives** are [here](https://github.com/tmarktaylor/phmdoctest/blob/master/README.md#directives).

It would work on code blocks and not work on Python interactive session blocks (doctests).

Such a feature is really a more general way of doing the `<!--phmdoctest-mark.skip-->` directive where ATTRIBUTE is replaced with skip.

**Comment by tmarktaylor** [comment]
Created version 1.4.0 that includes this enhancement.
[on PYPI](https://pypi.org/project/phmdoctest/1.4.0/)
